---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:1.0  # Replace with the actual image name and tag
        ports:
        - containerPort: 8000
        env:
        - name: USERS_SERVICE_URL
          value: "http://users:8000"
        - name: ORDERS_SERVICE_URL
          value: "http://orders:8000"
        - name: SUPPLIERS_SERVICE_URL
          value: "http://suppliers:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: user:1.0  # Replace with the actual image name and tag
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: order:1.0  # Replace with the actual image name and tag
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suppliers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suppliers
  template:
    metadata:
      labels:
        app: suppliers
    spec:
      containers:
      - name: suppliers
        image: supplier:1.0  # Replace with the actual image name and tag
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: suppliers-service
spec:
  selector:
    app: suppliers
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
